# https://fabricmc.net/develop/
minecraft_version=26.2-snapshot-5
loader_version=0.19.2
loom_version=1.16-SNAPSHOT
fabric_api_version=0.147.1+26.2

# https://www.midnightdust.eu/wiki/midnightlib/
midnightlib_version = 1.9.2+26.1-fabric

# https://docs.papermc.io/adventure/platform/fabric/
adventure_platform_fabric_version=6.9.0-SNAPSHOT

# Mod Properties
mod_version = 1.4.0
maven_group = me.mrsam7k
archives_base_name = SplashChanger
